services:
  server:
    image: ghcr.io/sinncrowley/crowleys_cloud/crowleys-cloud-server:v0.6.0
    build:
      context: ../
      dockerfile: server/Dockerfile
    container_name: crowleys_cloud_server
    ports:
      - "8080:8080"
    volumes:
      - ./storage:/app/storage
      - ./data:/app/data
      - ./logs:/app/logs
      - ./config:/app/config
    restart: always
